### ISSUE TITLE
OSC crashes on boot with corrupted profile

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/iio-oscilloscope#127] opened 2019-02-08 23:34 UTC
This happens a lot on Windows. A bad profile is created and auto-loaded when hardware is attached then OSC crashes without error or anything opening. Unplugging the hardware device and relaunching OSC fixes this or removing the profile file.

**Comment by rgetz** [comment] 2019-03-01 13:01
I think this might be related to serial number and uri / usb processing - partial patch at #137

**Comment by dNechita** [comment] 2020-07-27 08:54
@tfcollins is this stil happening? With the latest master I can't reproduce it.

**Comment by dNechita** [comment] 2020-08-03 08:17
It is likely that this has been fixed during the partial patch mentioned above.
Closing this.

**Closed by dNechita** 2020-08-03 08:17 UTC
Labels: bug
